version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zed_venezuela
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: 28076448
    ports:
      - "3308:3306"  # Cambiar a 3308:3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: gabriel
      DB_PASSWORD: 28076448
      DB_NAME: zed_venezuela
      DB_PORT: 3306  # Mantén esto como 3306 porque es el puerto dentro del contenedor

volumes:
  db_data:
